// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXY6BBsI4CwTzAecDDH1m0N_7GX-Wu-yM',
    appId: '1:744829665405:web:63c59b81579d3e316f3114',
    messagingSenderId: '744829665405',
    projectId: 'btlmoneymanagement',
    authDomain: 'btlmoneymanagement.firebaseapp.com',
    storageBucket: 'btlmoneymanagement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwGgvcGLhHEBM8tz5TqHYCaa2G263U9o',
    appId: '1:744829665405:android:183449fa13856c656f3114',
    messagingSenderId: '744829665405',
    projectId: 'btlmoneymanagement',
    storageBucket: 'btlmoneymanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3dW9CUoqR9JYVCr4-U1RaabkBshHk8k',
    appId: '1:744829665405:ios:eca124002a1464696f3114',
    messagingSenderId: '744829665405',
    projectId: 'btlmoneymanagement',
    storageBucket: 'btlmoneymanagement.firebasestorage.app',
    iosBundleId: 'com.example.btlQuanlychitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy3dW9CUoqR9JYVCr4-U1RaabkBshHk8k',
    appId: '1:744829665405:ios:eca124002a1464696f3114',
    messagingSenderId: '744829665405',
    projectId: 'btlmoneymanagement',
    storageBucket: 'btlmoneymanagement.firebasestorage.app',
    iosBundleId: 'com.example.btlQuanlychitieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXY6BBsI4CwTzAecDDH1m0N_7GX-Wu-yM',
    appId: '1:744829665405:web:1fe54bb5fb9ca8416f3114',
    messagingSenderId: '744829665405',
    projectId: 'btlmoneymanagement',
    authDomain: 'btlmoneymanagement.firebaseapp.com',
    storageBucket: 'btlmoneymanagement.firebasestorage.app',
  );
}
